fix syntax in ci/cd

diff --git a/.github/workflows/deploy-credentialserver.yml b/.github/workflows/deploy-credentialserver.yml
--- a/.github/workflows/deploy-credentialserver.yml
+++ b/.github/workflows/deploy-credentialserver.yml
@@ -10,26 +10,27 @@ on:
       - 'pigate/pkg/**'
       - 'pigate/configs/credentialserver-config.toml'
 
-deploy-credentialserver:
-  runs-on: [ self-hosted, Windows, pigate-cred ]
-  steps:
-    - name: Checkout repo
-      uses: actions/checkout@v4
+jobs:
+  deploy-credentialserver:
+    runs-on: [ self-hosted, Windows, pigate-cred ]
+    steps:
+      - name: Checkout repo
+        uses: actions/checkout@v4
 
-    - name: Build Credential Server
-      run: |
-        go build -o credentialserver.exe ./pigate/cmd/credentialserver/main.go
+      - name: Build Credential Server
+        run: |
+          go build -o credentialserver.exe ./pigate/cmd/credentialserver/main.go
 
-    - name: Copy Config and Binary to Service Directory
-      run: |
-        mkdir C:\Services\credentialserver 2>NUL
-        copy credentialserver.exe C:\Services\credentialserver\
-        copy pigate\configs\credentialserver-config.toml C:\Services\credentialserver\
+      - name: Copy Config and Binary to Service Directory
+        run: |
+          mkdir C:\Services\credentialserver 2>NUL
+          copy credentialserver.exe C:\Services\credentialserver\
+          copy pigate\configs\credentialserver-config.toml C:\Services\credentialserver\
 
-    - name: (Re)Install Windows Service
-      run: |
-        nssm stop credentialserver || echo "Service not found, continuing"
-        nssm remove credentialserver confirm || echo "Service not found, continuing"
-        nssm install credentialserver C:\Services\credentialserver\credentialserver.exe
-        nssm set credentialserver AppParameters -c C:\Services\credentialserver\
-        nssm start credentialserver
+      - name: (Re)Install Windows Service
+        run: |
+          nssm stop credentialserver || echo "Service not found, continuing"
+          nssm remove credentialserver confirm || echo "Service not found, continuing"
+          nssm install credentialserver C:\Services\credentialserver\credentialserver.exe
+          nssm set credentialserver AppParameters -c C:\Services\credentialserver\
+          nssm start credentialserver
